### PR TITLE
Make plugin compatible with CNPG 1.29

### LINKED ISSUE #115: Plugin is incompatible with CNPG 1.29
I'm using the samples files to create a stanza on Azure and a Cluster.
Everything is working well (archiving and backup).

Then I try to create a restored Cluster from this backup (I also use the sample file).
It doesn't work and I can see multiple recovery pod being created : 

```console
k get pod
NAME                                     READY   STATUS    RESTARTS   AGE
cluster-restored-1-full-recovery-8vmzq   0/2     Error     0          5m18s
cluster-restored-1-full-recovery-hjbsm   2/2     Running   0          48s
cluster-restored-1-full-recovery-j5png   0/2     Error     0          3m15s
cluster-restored-1-full-recovery-tbbc4   0/2     Error     0          7m27s
```

I can see that the container in Error is the `full-recovery` one : 

```
M1    full-recovery         ●  ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie          false  Error             0 off:off:off  │
```

In the logs, the Pod is well started and PostgreSQL as well :
```json
{
  "level": "info",
  "ts": "2026-04-14T09:46:40.937557826Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "cluster-restored-1-full-recovery",
  "record": {
    "log_time": "2026-04-14 09:46:40.935 UTC",
    "process_id": "44",
    "session_id": "69de0d00.2c",
    "session_line_num": "2",
    "session_start_time": "2026-04-14 09:46:40 UTC",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "00000",
    "message": "starting PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit",
    "backend_type": "postmaster",
    "query_id": "0"
  }
}
{
  "level": "info",
  "ts": "2026-04-14T09:46:40.937661899Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "cluster-restored-1-full-recovery",
  "record": {
    "log_time": "2026-04-14 09:46:40.935 UTC",
    "process_id": "44",
    "session_id": "69de0d00.2c",
    "session_line_num": "3",
    "session_start_time": "2026-04-14 09:46:40 UTC",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "00000",
    "message": "listening on IPv4 address \"127.0.0.1\", port 5432",
    "backend_type": "postmaster",
    "query_id": "0"
  }
}
```

The restoration finished when this log appears
"could not restore file \"00000002.history\" from archive: command not found"
which is normal in PostgreSQL recovery process.

But the startu process (launch by pg_ctl) exited : 
```json
{
  "level": "info",
  "ts": "2026-04-14T09:46:41.086538515Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "cluster-restored-1-full-recovery",
  "record": {
    "log_time": "2026-04-14 09:46:41.086 UTC",
    "process_id": "44",
    "session_id": "69de0d00.2c",
    "session_line_num": "5",
    "session_start_time": "2026-04-14 09:46:40 UTC",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "00000",
    "message": "startup process (PID 51) exited with exit code 1",
    "backend_type": "postmaster",
    "query_id": "0"
  }
}
{
  "level": "info",
  "ts": "2026-04-14T09:46:41.086618445Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "cluster-restored-1-full-recovery",
  "record": {
    "log_time": "2026-04-14 09:46:41.086 UTC",
    "process_id": "44",
    "session_id": "69de0d00.2c",
    "session_line_num": "6",
    "session_start_time": "2026-04-14 09:46:40 UTC",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "00000",
    "message": "aborting startup due to startup process failure",
    "backend_type": "postmaster",
    "query_id": "0"
  }
}
```

Errors returned: 

```json
{
  "level": "error",
  "ts": "2026-04-14T09:46:41.101098653Z",
  "msg": "Error while restoring a backup",
  "logging_pod": "cluster-restored-1-full-recovery",
  "error": "
  "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.3.3/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/restore.go:79\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.(*restoreRunnable).Start\n\tinternal/cmd/manager/instance/restore/restore.go:62\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/manager/runnable_group.go:260"
}
```

"While activating instance"

```json
{
  "level": "error",
  "ts": "2026-04-14T09:46:41.104266362Z",
  "msg": "restore error",
  "logging_pod": "cluster-restored-1-full-recovery",
  "error": "while restoring cluster: while activating instance: error starting PostgreSQL instance: exit status 1",
  "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.3.3/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func1\n\tinternal/cmd/manager/instance/restore/cmd.go:101\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1015\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1148\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1071\nmain.main\n\tcmd/manager/main.go:71\nruntime.main\n\t/opt/hostedtoolcache/go/1.26.1/x64/src/runtime/proc.go:290"
}
```

"While restoring instance".

**I do not have this issue with CloudNativePG in v1.28.**2, so I guess the plugin is missing something to work with 1.29.

 _I'm looking for what can explain that in release or code_

### PR DESCRIPTION
**Pull request by l00ptr**
Since this commit:
https://github.com/cloudnative-pg/cloudnative-pg/commit/6073919efe19a85157db1de5467e631b0ffc738f

restore_command is no longer removed from the postgresql.auto.conf by CNPG, so we now make sure pgbackrest write a postgresql.auto.conf that will work with CNPG (using the manager instead of calling pgbackrest).

Since we upgrade the CNPG dependency, we also upgrade other libs (mainly indirect dependencies through CNPG).

### CODE REVIEW

File: internal/restore/restore.go [hunk 1]
```diff
@@ -114,18 +114,24 @@ func (impl JobHookImpl) Restore(
 		return nil, err
 	}
 	env = append(env, recovEnv...)
+	// Unfortunately, we need to override the recovery_command (through the
+	// pgbackrest recovery option) instead of letting pgBackRest generate it.
```
Comment (pchovelon) [inline internal/restore/restore.go:118]:
```suggestion
	// pgbackrest --recovery-option option) instead of letting pgBackRest generate it.
```

**Comment by pchovelon** [comment]
Ok for the code. But if we want to merge like that, we should alert in documentation that CNPG must be >= 1.29

File: internal/restore/restore.go (hunk 1 above)
Comment (l00ptr) [reply internal/restore/restore.go:118]: We don't use the flag, so I won't include it in the comment. There are several ways to write the[ "Recovery Option" option](https://pgbackrest.org/configuration.html#section-restore/option-recovery-option): we can use `PGBACKREST_RECOVERY_OPTION` env (this is what we do), `--recovery-option` (we don't use it) or `recovery-option`.

**Comment by l00ptr** [comment]
> Ok for the code. But if we want to merge like that, we should alert in documentation that CNPG must be >= 1.29

it's now compatible with both 1.28 and 1.29. @pchovelon could you test or review that MR argain?

File: internal/restore/restore.go [hunk 2]
```diff
@@ -114,18 +114,35 @@ func (impl JobHookImpl) Restore(
...
+	//
+	// On CNPG < 1.29, the restore command generated  by pgBackRest is removed from
```
Comment (OrioQuezac) [inline internal/restore/restore.go]:
```suggestion
	// On CNPG < 1.29, the restore command generated by pgBackRest is removed from
```

File: internal/restore/restore.go [hunk 3]
```diff
@@ -114,18 +114,35 @@ func (impl JobHookImpl) Restore(
...
+	// postgresql.auto.conf by CNPG. However, this is no longer true since the that
```
Comment (OrioQuezac) [inline internal/restore/restore.go]:
```suggestion
	// postgresql.auto.conf by the operator. However, this is no longer true since the that
```
To prevent “CNPG” from appearing twice in this sentence.

**Review by OrioQuezac — APPROVED** [review]
